In [1]:
from tensorflow_probability.python.distributions import Normal
import gym
from actor import Actor
import tensorflow as tf
import os
from datetime import datetime
import numpy as np
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)

In [2]:
actor = Actor()
adam = tf.keras.optimizers.Adam()

In [3]:
checkpoint_directory_a = "./training_checkpoints/actor"
checkpoint = tf.train.Checkpoint(optimizer=adam, model=actor)
status = checkpoint.restore(tf.train.latest_checkpoint(checkpoint_directory_a))

In [4]:
def get_action_distribution(actor, state):
    mu, sigma = actor(state)
    return Normal(loc=mu, scale=sigma)

In [5]:
env = gym.make('LunarLanderContinuous-v2')
all_returns = 0
for _ in range(200):    
    cum_return = 0 
    state = env.reset()
    while True:
        env.render()
        state = np.reshape(state, (1,1,8))
        action = get_action_distribution(actor, state).sample()[0]
        state, reward, done, _ = env.step(action)
        cum_return += reward
        if done:
            break
    print(cum_return)
    all_returns += cum_return
print(cum_return / 200)

ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [1, 8]

In [5]:
actor(np.zeros((1,10,8)))

(<tf.Tensor: shape=(1, 10, 2), dtype=float32, numpy=
 array([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 10, 2), dtype=float32, numpy=
 array([[[0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472],
         [0.6931472, 0.6931472]]], dtype=float32)>)

In [4]:
actor.lstm1.states

[<tf.Variable 'actor/lstm/Variable:0' shape=(1, 64) dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       dtype=float32)>,
 <tf.Variable 'actor/lstm/Variable:0' shape=(1, 64) dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       dtype=float32)>]

In [9]:
type(actor.lstm2.states)

list

In [18]:
actor.lstm1.input

AttributeError: Layer lstm_2 is not connected, no input to return.

In [17]:
actor.lstm1.reset_states()